# Leader
set -g prefix c-a

set -g mouse on

# Don't wait for key inputs after certain keys are pressed
set -s escape-time 1 # When 0, garbage gets inserted from wezterm
set-option -g repeat-time 500

# Colors
set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',*256col*:Tc'

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Reload config
# <Leader>r
unbind r
bind r source-file ~/.tmux.conf

# Plugins
# <Leader>I to install
# <Leader>U to update
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'niksingh710/minimal-tmux-status'

# Statusline
set -g @minimal-tmux-fg "#181926" # hl text
set -g @minimal-tmux-bg "#F0C6C6" # hl bg
set -g @minimal-tmux-status-right " "
set -g @minimal-tmux-use-arrow false
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
set -g @minimal-tmux-justify "left" # left | right | centre
set -g @minimal-tmux-status "bottom"
set -g status-left "#(echo #{pane_current_path} | sed 's#$HOME#~#g')"

# Pane separator
set -g pane-active-border-style bg=default,fg=white
set -g pane-border-style fg="#666667"

# Window navigation
bind-key -n M-0 select-window -t :0
bind-key -n M-1 select-window -t :1
bind-key -n M-2 select-window -t :2
bind-key -n M-3 select-window -t :3
bind-key -n M-4 select-window -t :4
bind-key -n M-5 select-window -t :5
bind-key -n M-6 select-window -t :6
bind-key -n M-7 select-window -t :7
bind-key -n M-8 select-window -t :8
bind-key -n M-9 select-window -t :9

run '~/.tmux/plugins/tpm/tpm'
