general.import = [
    "~/.config/alacritty/tokyobones_dark.toml",
]

window.decorations = "None"
window.opacity = 1
window.padding = { x = 20, y = 0 }

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "iosevka"
style = "Regular"
[font.bold]
family = "iosevka"
style = "Regular"
[font.bold_italic]
family = "iosevka"
style = "Regular"
[font.italic]
family = "iosevka"
style = "Italic"
